### PR TITLE
Add sync function that throws error support

### PR DESCRIPTION
**Pull request by nofar9792**
The bug: ```waitFor``` that runs sync function that throws errors doesn't use retry.
Solution: primisify the function

### CODE REVIEW

**Review by AlonMiz — COMMENTED** [review]
Looks good pls add a test

**Comment by AlonMiz** [comment]
The coverage should be 100% 😀

**Comment by AlonMiz** [comment]
Actually we dont need 142 anymore
Cause you are promisifying anyway 😀
So pls remove the old promisification

**Comment by nofar9792** [comment]
@AlonMiz done

**Comment by AlonMiz** [comment]
Amazing thanks!

**Review by AlonMiz — APPROVED** [review]

**Pull request merged**
